site_name: DotPack
# edit_uri: edit/v2/docs/
site_description: the docs
repo_url: https://github.com/example/repository/
repo_name: DotPack
site_author: XavierChan
theme:
  name: material
  language: zh
  logo: logo.png
  favicon: dotpack.ico
  palette:
    primary: 'Light Blue'
    accent: 'Light Blue'
  feature:
    tabs: false
extra_css:
  - css/extra.css
  - https://cdn.jsdelivr.net/gh/fengyuanchen/viewerjs/dist/viewer.css
  - https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css
extra_javascript:
  - https://cdn.jsdelivr.net/gh/fengyuanchen/viewerjs/dist/viewer.js
  - https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js
  - js/docSearch.js
  - js/imageHelper.js

markdown_extensions:
  # - markdown_include.include:
  #     base_path: docs
  - markdown.extensions.attr_list
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  # - pyembed.markdown

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 简体中文
      link: /zh/
      lang: zh

# Navigation
nav:
  - Introduction: 'zh/index.md'
  - Getting Started:
    - MiniApp: 'zh/play/miniapp.md'
    - Scratch: 'zh/play/scratch.md'
    - MicroBlocks: 'zh/play/microblocks.md'
    - Python: 'zh/play/python.md'
  - Examples: 'zh/examples.md'
  - Education:
    - Pixel: 'courses/pixel.md'
    - Position: 'courses/position.md'
    - Color: 'courses/color.md'
    - Animation: 'courses/animation.md'
    - Python: 'courses/python.md'
  - Ideas: 'zh/ideas.md'
  - PlayGround: 'index.md'
  - Tools: 'zh/tools.md'
  - Firewares: 'zh/firewares.md'
  - API Reference: 'api_reference.md'
  - Release Notes: 'zh/release_notes.md'
  - FAQ: 'zh/faq.md'
